### ISSUE TITLE
Game wouldn't save, veinmining started simply destroying the blocks

### ISSUE THREAD

**Issue by bloodconfetti** [oOBoomberOo/veinminer#1] opened 2019-08-22 22:02 UTC
I'm really really sorry. Idiot me didn't save the log...

I had to use the task manager to close MC down, then wanted to make certain it was actually this datapack that caused issues. So I removed it, then re-opened MC, was able to mine blocks again, and save the game.

I know this won't be of much help :/ I'm so sorry... But I thought I should let you know anyway. Was loving the mod while it worked.

**Comment by oOBoomberOo** [comment] 2019-08-22 22:35
Thanks for the bug report! however, I can't reproduce this bug.
Can you try make a copy of your world and test it again with my datapack installed?

**Comment by oOBoomberOo** [comment] 2019-08-25 13:04
This is fixed in v1.0.2

**Closed as completed by oOBoomberOo** 2019-08-25 13:04 UTC
Labels: bug
